version: 2
jobs:
  build:
    working_directory: ~/lookbook
    docker:
      - image: circleci/node:latest-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Dependencies
          command: npm install --no-audit --no-save
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Test
          command: npm test
      - store_test_results:
          path: test-output
      - store_artifacts:
          path: test-output
      - run:
          name: Build distributable .css file
          command: npm run build
      - store_artifacts:
          path: dist
