version: 2.1
jobs:
  build:
    working_directory: ~/lookbook
    docker:
      - image: cimg/node:20.17.0-browsers
        environment:
            NODE_ENV: development
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run: npm install --no-audit --no-save

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
            
      - run: npm test
      - run: npm run build

      - store_artifacts:
          path: dist
