#!/usr/bin/env bash
set -eo pipefail

source "$(dirname "$0")/config.sh"

# Relative to $LOOKBOOK_SRC
all=lookbook.css
base=base.css
utils=utils.css

ext=css
ext_min_maps=dist.css
ext_min=bare.css

build_file () {
  local file_path="$LOOKBOOK_SRC/$1"
  local out=`basename $1 .css`

  # Emit minified and sourcemapped into dist/<file>.dist.css
  echo "🕐 Start $LOOKBOOK_DIR/$out.$ext_min_maps"
  NODE_ENV=production npx postcss "$file_path" --dir "$LOOKBOOK_DIR" --ext "$ext_min_maps" --verbose

  # Emit non-minified into dist/<file>.css
  # Meant for being included in other projects, before minification and source mapping
  echo "🕐 Start $LOOKBOOK_DIR/$out.css"
  NODE_ENV=development npx postcss "$file_path" --no-map --dir "$LOOKBOOK_DIR" --verbose

  # Emit minified, non-sourcemap dist/<file>.bare.css
  echo "🕐 Start $LOOKBOOK_DIR/$out.$ext_min"
  NODE_ENV=production npx postcss "$file_path" --no-map --ext "$ext_min" --dir "$LOOKBOOK_DIR" --verbose
}

format_file () {
  local file=$1
  echo "🕐 Formatting $LOOKBOOK_DIR/$file..."
  prettier --write "$LOOKBOOK_DIR/$file"
}

print_size () {
  local file=`basename $1 .css`

  local size_nonminified="$(ls -lah $LOOKBOOK_DIR/$file.$ext | awk -F " " {'print $5'})"
  echo "✅ $LOOKBOOK_DIR/$file.$ext ($size_nonminified)"

  local size_nonmap="$(ls -lah $LOOKBOOK_DIR/$file.$ext_min | awk -F " " {'print $5'})"
  echo "✅ $LOOKBOOK_DIR/$file.$ext_min ($size_nonmap)"

  local size="$(ls -lah $LOOKBOOK_DIR/$file.$ext_min_maps | awk -F " " {'print $5'})"
  echo "✅ $LOOKBOOK_DIR/$file.$ext_min_maps ($size)"
}

run_pipeline () {
  echo "🚀 Building $1..."
  echo "----------------------------------"
  build_file $1
  format_file $1
  print_size $1
  echo "✨ Done with $1"
  echo "----------------------------------"
}

run_pipeline $all

run_pipeline $base

run_pipeline $utils
