#!/usr/bin/env bash

file=src/lookbook.css
dir=dist

echo "🕐 Building $file..."

# Emit minified and sourcemapped dist/lookbook.css
NODE_ENV='production' npx postcss "$file" --dir "$dir" --ext dist.css "$@"

status=$?

# Emit non-minified dist/lookbook.css
# Meant for being included in other projects, before minification and source mapping
NODE_ENV='development' npx postcss "$file" --no-map --dir "$dir" "$@"

size_nonminified="$(ls -lah dist/lookbook.css | awk -F " " {'print $5'})"
echo "✅ Built non-minified version into $dir/lookbook.css ($size_nonminified)"

size="$(ls -lah dist/lookbook.dist.css | awk -F " " {'print $5'})"

echo "✅ Built minified version (with sourcemaps) into $dir/lookbook.dist.css ($size)" && exit $status
