#!/usr/bin/env bash

# Read version string from user (like "2.0.1"). Then we build the distro files
# with the new version, commit and tag, and finally release the new .css files to CDN.

# PRECONS:
# --------------
# Do this before running the script:
#
# 1. Bump version string in package.json
# 2. Done! Run scripts/release

jq_exists=$(command -v jq)

# If user has jq installed, read `version` from package.json. Else, ask for it on the prompt.
if [ ! -z "$jq_exists" ]; then
  version=$(cat package.json | jq -r ".version")  # -r for raw strings
else
  read -p "Which version should we release? (without any prefix, please. E.g. '2.0.1'): " version
fi

echo "🕐 Releasing $version..."

npm install && \
  npm run build && \
  git add package.json package-lock.json dist && git commit -m "$version" && \
  git tag "$version" && \
  git push origin && git push --tags origin && \
  scripts/distribute "dist/*.css"
