#!/usr/bin/env bash
set -eo pipefail

source "$(dirname "$0")/config.sh"

LOOKBOOK_ENV=${NODE_ENV:-development}

# Emit non-minified into dist/<file>.css
# Meant for being included in other projects, before minification and source mapping
NODE_ENV=$LOOKBOOK_ENV npx postcss $LOOKBOOK_INPUT_FILE \
  --watch \
  --verbose \
  --no-map \
  --dir $LOOKBOOK_DIR
